image: toc-build:latest

script:
  - gulp lint
  - Xvfb :1 -screen 0 1024x768x24 -ac &
  - gulp test --prod

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
