image: toc-build:latest

env:
  - BITBUCKET_OAUTH_TOKEN=$BITBUCKET_OAUTH_TOKEN
  
script:
  - Xvfb :1 -screen 0 1024x768x24 -ac &
  - gulp verify --prod

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    recipients:
      - toc-dev@lewisl.net
