image: lewisl9029/toc-dev:latest

git:
  depth: 1

script:
  - gulp lint
  - Xvfb :1 -screen 0 1024x768x24 &
  - gulp test-unit
  - gulp build
  #gulp test-unit --prod
  - gulp test-e2e --prod

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
