image: toc-build:latest

script:
  - gulp lint
  - karma start --singleRun

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
