image: toc-test:latest

git:
  depth: 100

script:
  - gulp lint
  - xvfb-run -n 1 --server-args="-screen 0, 1024x768x24" karma start --singleRun
  - http-server ./www -p 8100 &
  - xvfb-run -n 1 --server-args="-screen 0, 1024x768x24" protractor
  - kill %1

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
