image: toc-test:latest

git:
  depth: 100

script:
  - xvfb-run -n 1 --server-args="-screen 0, 1024x768x24" gulp verify

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
