image: toc-build:latest

git:
  depth: 50

script:
  - xvfb-run -n 1 --server-args="-screen 0, 1366x768x24" gulp verify --prod

deploy:
  bash:
    command: source ./drone-deploy.sh

notify:
  email:
    on_success: change
    on_failure: change, blame
    recipients:
      - toc-drone@lewisl.net
